project:
  render:
    - ./presentation/*.qmd

format:
# NOTE: PDF Notes
  titlepage-pdf:
    # NOTE: Titlepages opts
    titlepage: academic
    titlepage-logo: "./resources/logos/gv_logo_2c.png"
    titlepage-theme:
      elements: ["\\headerblock", "\\logoblock", "\\titleblock", "\\authorblock"]
      page-align: "center"
      title-style: "doublelinetight"
      title-fontstyle: ["Large", "bfseries"]
      title-fontfamily: "Liberation Sans"
      title-space-after: "1.5cm"
      subtitle-fontstyle: "Large"
      subtitle-fontfamily: "Liberation Sans"
      author-style: "two-column"
      affiliation-style: "none"
      affiliation-fontstyle: "small"
      affiliation-fontfamily: "Liberation Sans"
      author-space-after: "1.5cm"
      author-fontstyle: "small"
      author-fontfamily: "Liberation Sans"
      logo-space-after: "2\\baselineskip"
      logo-size: 250pt
      header-fontstyle: ["textsc", "LARGE"]
      header-space-after: "1.5cm"
      header-fontfamily: "Liberation Sans"
    # NOTE: PDF opts
    toc-title: "Table of Contents"
    toc: true
    toc-depth: 3
    lof: false
    lot: false
    number-depth: 3
    number-sections: true
    keep-tex: false
    keep-md: false
    # NOTE: LaTeX opts
    include-in-header:
      - file: "./resources/tex/header.tex"
    include-before-body:
      - file: "./resources/tex/before_body.tex"
    template: ./resources/tex/template.tex
    template-partials:
      - ./resources/tex/doc-class.tex
      - ./resources/tex/toc.tex
    # NOTE: Rendering opts
    engine: knitr
    documentclass: article
    pdf-engine: lualatex
    geometry: "margin=1in"
    papersize: letter
    output-ext: pdf
    # NOTE: Link opts
    colorlinks: true
    linkcolor: gvblue
    toccolor: black
    filecolor: gvblue
    urlcolor: gvblue
    citecolor: gvblue
    # NOTE: Font and language opts
    mainfont: "Liberation Sans"
    fontsize: 12pt
    microtypeoptions: 
      - protrusion = true
      - expansion = true
    hyperrefoptions:
      - pdfpagemode=UseOutlines
    lang: en-US
    fontenc: T1
    # NOTE: Code opts
    highlight-style: a11y
    # NOTE: Fig and tbl opts
    fig-align: center
    cap-location: top
    fig-cap-location: top
    tbl-cap-location: top
    fig-pos: H
    tbl-pos: H
    fig-width: 6
    fig-height: 3
  # NOTE: RevealJS Slides Light Theme
  revealjs:
    theme: ./resources/theme/gv_theme_light.scss
    css: ./resources/theme/gv_style_light.css
    pointer:
      color: blue
    logo: ./resources/logos/gv_logo_2c.png
    # NOTE: Graphics and tables
    mermaid-format: svg
    fig-format: svg
